version: "3.8"

services:
  node:
    image: tezos-${NETWORK}-node-setup-from-snapshot
    build:
      context: .
      dockerfile: node.dockerfile
      args:
        IMAGE: ${IMAGE}
        STARTUP_SCRIPT: ${STARTUP_SCRIPT}
    hostname: node
    entrypoint: /bin/sh ${STARTUP_SCRIPT}
    environment:
      - NETWORK=$NETWORK
      - P2P_PORT=${P2P_PORT_CONTAINER}
      - RPC_PORT=${RPC_PORT_CONTAINER}
      - SNAPSHOT_PATH=${SNAPSHOT_PATH}
      - SNAPSHOT_FILE=${SNAPSHOT_FILE}
      - SNAPSHOT_URL=${SNAPSHOT_URL}
      - TEZOS_NODE_DATA=${TEZOS_NODE_DATA}
      - TEZOS_CLIENT_DATA=${TEZOS_CLIENT_DATA}
    tty: true
    ports:
      - "${RPC_PORT_HOST}:${RPC_PORT_CONTAINER}"
      - "${P2P_PORT_HOST}:${P2P_PORT_CONTAINER}"
    user: "${UID}:${GID}"      
    volumes:
      - ./data/${NETWORK}/node:${TEZOS_NODE_DATA}
      - ./data/${NETWORK}/client:${TEZOS_CLIENT_DATA}
      - ./snapshot:${SNAPSHOT_PATH}
    restart: on-failure
